// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cliqx.cupom.api;

#nullable disable

namespace cliqx.cupom.api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cliqx.cupom.api.Cupom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CodigoCupom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PercentualDesconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TipoCupom")
                        .HasColumnType("int");

                    b.Property<int>("TipoDesconto")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("cupom");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CodigoCupom = "PRIMEIRACOMPRA",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2023, 9, 25, 10, 44, 39, 321, DateTimeKind.Local).AddTicks(3870),
                            DataValidade = new DateTime(2028, 9, 25, 10, 44, 39, 321, DateTimeKind.Local).AddTicks(3852),
                            Descricao = "Destinado a usuários de primeira compra",
                            PercentualDesconto = 30m,
                            TipoCupom = 2,
                            TipoDesconto = 2,
                            Usuario = "SNOG",
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 2L,
                            CodigoCupom = "ANIVERSARIO",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2023, 9, 25, 10, 44, 39, 321, DateTimeKind.Local).AddTicks(3874),
                            DataValidade = new DateTime(2024, 9, 25, 10, 44, 39, 321, DateTimeKind.Local).AddTicks(3874),
                            Descricao = "Destinado a quem faz aniversário",
                            PercentualDesconto = 0m,
                            TipoCupom = 1,
                            TipoDesconto = 1,
                            Usuario = "SNOG",
                            ValorDesconto = 10m
                        });
                });

            modelBuilder.Entity("cliqx.cupom.api.CupomLimiteCpf", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantidadeLimite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("cupom_limite_cpf");
                });

            modelBuilder.Entity("cliqx.cupom.api.CupomUsoPedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CupomId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("cupom_uso_pedido");
                });
#pragma warning restore 612, 618
        }
    }
}
